[package]
name = "vpktool"
version = "0.1.0"
authors = ["SSB64d team <unknown>"]
edition = "2018"

[dependencies]
structopt = {version = "0.3.12", default-features = false}
libvpk = {path = "../libvpk"}
anyhow = "1.0.27"
