[package]
name = "libvpk"
version = "0.1.0"
authors = ["SSB64d team <unknown>"]
edition = "2018"

[dependencies]
byteorder = "1.3.1"
bitstream-io = "0.8.2"
err-derive = "0.2.3"
log = "0.4.6" 

[dev-dependencies]
simple_logger = "1.3.0"
