format = 'ci'
bitdepth = 4
width = 16
height = 16
images = [
    '01CF00.ci4.png',
    '01CF80.ci4.png',
    '01D000.ci4.png',
    '01D080.ci4.png',
    '01D100.ci4.png',
    '01D180.ci4.png',
    '01D200.ci4.png',
    '01D280.ci4.png',
    '01D300.ci4.png',
    '01D380.ci4.png',
    '01D400.ci4.png',
    '01D480.ci4.png',
    '01D500.ci4.png',
    '01D580.ci4.png',
    '01D600.ci4.png',
]
