[raw]
"game/audio/tempbins/S1_music.sbk" = {size = 0x26E10, us = 0xB277B0}
"game/audio/tempbins/B1_sounds1.ctl" = {size = 0x6720, us = 0xB4E5C0}
"game/audio/tempbins/B1_sounds1.tbl" = {size = 0x116970, us = 0xB54CE0}
"game/audio/tempbins/B1_sounds2.ctl" = {size = 0xFBA0, us = 0xC6B650}
"game/audio/tempbins/B1_sounds2.tbl" = {size = 0x2DC1E0, us = 0xC7B1F0}
"game/unknown/tempbins/F573D0.bin" = {size = 0x820, us = 0xF573D0}
"game/unknown/tempbins/F57BF0.bin" = {size = 0x2DD0, us = 0xF57BF0}
"game/unknown/tempbins/F5A9C0.bin" = {size = 0x4B20, us = 0xF5A9C0}

# Code .text/.data/.rodata binaries
"game/asm/boot/boot.raw.bin" = {us = 0x40, size = 0xfc0}
"game/asm/system/system.raw.bin" = {us = 0x1000, size = 0x3f6d0}
"game/asm/ovl0/ovl0.raw.bin" = {us = 0x43220, size = 0xea70}
"game/asm/ovl2/ovl2.raw.bin" = {us = 0x51c90, size = 0x5a8b0}
"game/asm/ovl3/ovl3.raw.bin" = {us = 0xac540, size = 0x5b480}
"game/asm/ovl1/ovl1.raw.bin" = {us = 0x1079c0, size = 0x25f0}
"game/asm/ovl4/ovl4.raw.bin" = {us = 0x109fb0, size = 0x13c0}
"game/asm/ovl5/ovl5.raw.bin" = {us = 0x10b370, size = 0x5b0}
"game/asm/ovl65/ovl65.raw.bin" = {us = 0x10b920, size = 0x5ee0}
"game/asm/ovl6/ovl6.raw.bin" = {us = 0x111800, size = 0x20e0}
"game/asm/ovl7/ovl7.raw.bin" = {us = 0x1138e0, size = 0x38a0}
"game/asm/ovl10/ovl10.raw.bin" = {us = 0x117180, size = 0x2940}
"game/asm/ovl11/ovl11.raw.bin" = {us = 0x119ac0, size = 0x330}
"game/asm/ovl12/ovl12.raw.bin" = {us = 0x119df0, size = 0x550}
"game/asm/ovl13/ovl13.raw.bin" = {us = 0x11a340, size = 0x1630}
"game/asm/ovl14/ovl14.raw.bin" = {us = 0x11b970, size = 0x1120}
"game/asm/ovl17/ovl17.raw.bin" = {us = 0x11ca90, size = 0x1180}
"game/asm/ovl18/ovl18.raw.bin" = {us = 0x11dc10, size = 0x16a0}
"game/asm/ovl60/ovl60.raw.bin" = {us = 0x11f2b0, size = 0x1ca0}
"game/asm/ovl61/ovl61.raw.bin" = {us = 0x120f50, size = 0x1560}
"game/asm/ovl19/ovl19.raw.bin" = {us = 0x1224b0, size = 0x2e30}
"game/asm/ovl20/ovl20.raw.bin" = {us = 0x1252e0, size = 0x2dc0}
"game/asm/ovl21/ovl21.raw.bin" = {us = 0x1280a0, size = 0x18d0}
"game/asm/ovl22/ovl22.raw.bin" = {us = 0x129970, size = 0xb50}
"game/asm/ovl23/ovl23.raw.bin" = {us = 0x12a4c0, size = 0x980}
"game/asm/ovl24/ovl24.raw.bin" = {us = 0x12ae40, size = 0x4120}
"game/asm/ovl25/ovl25.raw.bin" = {us = 0x12ef60, size = 0xe20}
"game/asm/ovl26/ovl26.raw.bin" = {us = 0x12fd80, size = 0x9f80}
"game/asm/ovl27/ovl27.raw.bin" = {us = 0x139d00, size = 0x73e0}
"game/asm/ovl28/ovl28.raw.bin" = {us = 0x1410e0, size = 0x6a50}
"game/asm/ovl29/ovl29.raw.bin" = {us = 0x147b30, size = 0x5b40}
"game/asm/ovl30/ovl30.raw.bin" = {us = 0x14d670, size = 0x30d0}
"game/asm/ovl15/ovl15.raw.bin" = {us = 0x150740, size = 0x560}
"game/asm/ovl31/ovl31.raw.bin" = {us = 0x150ca0, size = 0x7da0}
"game/asm/ovl32/ovl32.raw.bin" = {us = 0x158a40, size = 0x5110}
"game/asm/ovl33/ovl33.raw.bin" = {us = 0x15db50, size = 0x4af0}
"game/asm/ovl34/ovl34.raw.bin" = {us = 0x162640, size = 0x31d0}
"game/asm/ovl35/ovl35.raw.bin" = {us = 0x165810, size = 0xee0}
"game/asm/ovl36/ovl36.raw.bin" = {us = 0x1666f0, size = 0x1140}
"game/asm/ovl37/ovl37.raw.bin" = {us = 0x167830, size = 0x1100}
"game/asm/ovl38/ovl38.raw.bin" = {us = 0x168930, size = 0x11b0}
"game/asm/ovl39/ovl39.raw.bin" = {us = 0x169ae0, size = 0x1130}
"game/asm/ovl40/ovl40.raw.bin" = {us = 0x16ac10, size = 0x1100}
"game/asm/ovl41/ovl41.raw.bin" = {us = 0x16bd10, size = 0x1160}
"game/asm/ovl42/ovl42.raw.bin" = {us = 0x16ce70, size = 0x1160}
"game/asm/ovl43/ovl43.raw.bin" = {us = 0x16dfd0, size = 0x1160}
"game/asm/ovl44/ovl44.raw.bin" = {us = 0x16f130, size = 0xc10}
"game/asm/ovl45/ovl45.raw.bin" = {us = 0x16fd40, size = 0x920}
"game/asm/ovl46/ovl46.raw.bin" = {us = 0x170660, size = 0xcc0}
"game/asm/ovl47/ovl47.raw.bin" = {us = 0x171320, size = 0xec0}
"game/asm/ovl48/ovl48.raw.bin" = {us = 0x1721e0, size = 0x980}
"game/asm/ovl49/ovl49.raw.bin" = {us = 0x172b60, size = 0xed0}
"game/asm/ovl50/ovl50.raw.bin" = {us = 0x173a30, size = 0xf10}
"game/asm/ovl51/ovl51.raw.bin" = {us = 0x174940, size = 0x980}
"game/asm/ovl52/ovl52.raw.bin" = {us = 0x1752c0, size = 0xc40}
"game/asm/ovl53/ovl53.raw.bin" = {us = 0x175f00, size = 0x15a0}
"game/asm/ovl54/ovl54.raw.bin" = {us = 0x1774a0, size = 0x10c0}
"game/asm/ovl55/ovl55.raw.bin" = {us = 0x178560, size = 0x27f0}
"game/asm/ovl56/ovl56.raw.bin" = {us = 0x17ad50, size = 0x37c0}
"game/asm/ovl57/ovl57.raw.bin" = {us = 0x17e510, size = 0x7b0}
"game/asm/ovl58/ovl58.raw.bin" = {us = 0x17ecc0, size = 0x540}
"game/asm/ovl59/ovl59.raw.bin" = {us = 0x17f200, size = 0x8cd0}
"game/asm/ovl62/ovl62.raw.bin" = {us = 0x187ed0, size = 0x2800}
"game/asm/ovl63/ovl63.raw.bin" = {us = 0x18a6d0, size = 0x1730}
"game/asm/ovl64/ovl64.raw.bin" = {us = 0x18be00, size = 0x1230}
"game/asm/ovl16/ovl16.raw.bin" = {us = 0x18d030, size = 0xc80}
"game/asm/ovl8/ovl8.raw.bin" = {us = 0x18dcb0, size = 0x1da00}
"game/asm/ovl9/ovl9.raw.bin" = {us = 0x1ab6b0, size = 0x11c0}

[spriteBanks]
dir = "game/sprites"
[[spriteBanks.us]]
    name = "bank1"
    spriteInfo = [0xAC7340, 0xAC9DE0]
    spriteBank = [0xAC9DE0, 0xB16C80]
[[spriteBanks.us]]
    name = "bank2"
    spriteInfo = [0xB16C80, 0xB17060]
    spriteBank = [0xB17060, 0xB174A0]
    entries = [
        "rock",
        "sphere",
        "particle",
    ]
[[spriteBanks.us]]
    name = "bank3"
    spriteInfo = [0xB174A0, 0xB176A0]
    spriteBank = [0xB176A0, 0xB19700]
[[spriteBanks.us]]
    name = "bank4"
    spriteInfo = [0xB19700, 0xB19850]
    spriteBank = [0xB19850, 0xB1BCA0]
[[spriteBanks.us]]
    name = "bank5"
    spriteInfo = [0xB1BCA0, 0xB1BDE0]
    spriteBank = [0xB1BDE0, 0xB1E640]
[[spriteBanks.us]]
    name = "bank6"
    spriteInfo = [0xB1E640, 0xB1E7E0]
    spriteBank = [0xB1E7E0, 0xB1F960]
[[spriteBanks.us]]
    name = "bank7"
    spriteInfo = [0xB1F960, 0xB1FC80]
    spriteBank = [0xB1FC80, 0xB22980]
[[spriteBanks.us]]
    name = "bank8"
    spriteInfo = [0xB22980, 0xB22A00]
    spriteBank = [0xB22A00, 0xB22C30]
[[spriteBanks.us]]
    name = "bank9"
    spriteInfo = [0xB22C30, 0xB22D40]
    spriteBank = [0xB22D40, 0xB277B0]

[resources]
dir = "game/resources/"
[resources.us]
    table = [0x1AC870, 0x1B2C6C]
