[package]
name = "libgfx"
version = "0.1.0"
authors = ["SSB64d team <unknown>"]
edition = "2018"

[features]
png = ["lodepng"]

[dependencies]
rgb = "0.8.13"
lodepng = {version = "2.6.0", optional = true}
