format = 'i'
bitdepth = 4
width = 32
height = 32
images = [
    '01DAF0_00.i4.png',
    '01DAF0_01.i4.png',
    '01DAF0_02.i4.png',
    '01DAF0_03.i4.png',
    '01DAF0_04.i4.png',
    '01DAF0_05.i4.png',
    '01DAF0_06.i4.png',
    '01DAF0_07.i4.png',
    '01DAF0_08.i4.png',
    '01DAF0_09.i4.png',
    '01DAF0_10.i4.png',
    '01DAF0_11.i4.png',
    '01DAF0_12.i4.png',
    '01DAF0_13.i4.png',
    '01DAF0_14.i4.png',
    '01DAF0_15.i4.png',
    '01DAF0_16.i4.png',
    '01DAF0_17.i4.png',
    '01DAF0_18.i4.png',
    '01DAF0_19.i4.png',
]
