format = 'ci'
bitdepth = 4
width = 32
height = 32
images = [
    '02FF30.ci4.png',
    '030130.ci4.png',
    '030330.ci4.png',
    '030530.ci4.png',
    '030730.ci4.png',
    '030930.ci4.png',
    '030B30.ci4.png',
    '030D30.ci4.png',
    '030F30.ci4.png',
]
