format = 'ci'
bitdepth = 4
width = 32
height = 32
images = [
    '0323A8_0.ci4.png',
    '0323A8_1.ci4.png',
    '0323A8_2.ci4.png',
    '0323A8_3.ci4.png',
    '0323A8_4.ci4.png',
    '0323A8_5.ci4.png',
    '0323A8_6.ci4.png',
    '0323A8_7.ci4.png',
]
