[package]
name = "n64gfx"
version = "0.1.0"
authors = ["SSB64d team <unknown>"]
edition = "2018"

[dependencies]
structopt = {version = "0.3.12", default-features = false}
libgfx = {path = "../libgfx"}
anyhow = "1.0.27"
lodepng = "2.5.0"

