[package]
name = "n64gfx"
version = "0.1.0"
authors = ["SSB64d team <unknown>"]
edition = "2018"

[dependencies]
libgfx = {path = "../libgfx"}
anyhow = "1.0.27"
lodepng = "2.5.0"
pico-args = "0.3.4"
indoc = "1.0.3"
