format = 'ci'
bitdepth = 4
width = 32
height = 32
images = [
    '02FED0_0.ci4.png',
    '02FED0_1.ci4.png',
    '02FED0_2.ci4.png',
    '02FED0_3.ci4.png',
    '02FED0_4.ci4.png',
    '02FED0_5.ci4.png',
    '02FED0_6.ci4.png',
    '02FED0_7.ci4.png',
    '02FED0_8.ci4.png',
]
