[package]
name = "imgbank"
version = "0.1.0"
authors = ["SSB64d team <unknown>"]
edition = "2018"

[dependencies]
anyhow = "1.0.27"
byteorder = "1.3.4" 
lodepng = "2.5.0"
libgfx = {path = "../libgfx"}
libsprite = {path = "../libsprite"}
toml = "0.5.6" 
pico-args = "0.3.4"
indoc = "1.0.3"
