format = 'i'
bitdepth = 4
width = 32
height = 32
images = [
    '01DB58.i4.png',
    '01DD58.i4.png',
    '01DF58.i4.png',
    '01E158.i4.png',
    '01E358.i4.png',
    '01E558.i4.png',
    '01E758.i4.png',
    '01E958.i4.png',
    '01EB58.i4.png',
    '01ED58.i4.png',
    '01EF58.i4.png',
    '01F158.i4.png',
    '01F358.i4.png',
    '01F558.i4.png',
    '01F758.i4.png',
    '01F958.i4.png',
    '01FB58.i4.png',
    '01FD58.i4.png',
    '01FF58.i4.png',
    '020158.i4.png',
]
