format = 'rgba'
bitdepth = 16
width = 32
height = 32
images = [
    '0004D0_0.rgba16.png',
    '0004D0_1.rgba16.png',
    '0004D0_2.rgba16.png',
    '0004D0_3.rgba16.png',
    '0004D0_4.rgba16.png',
]
