format = 'ci'
bitdepth = 4
width = 32
height = 32
images = [
    '032400.ci4.png',
    '032600.ci4.png',
    '032800.ci4.png',
    '032A00.ci4.png',
    '032C00.ci4.png',
    '032E00.ci4.png',
    '033000.ci4.png',
    '033200.ci4.png',
]
