format = 'rgba'
bitdepth = 32
width = 32
height = 32
images = [
    '034FA0.rgba32.png',
    '035FA0.rgba32.png',
    '036FA0.rgba32.png',
    '037FA0.rgba32.png',
    '038FA0.rgba32.png',
    '039FA0.rgba32.png',
    '03AFA0.rgba32.png',
    '03BFA0.rgba32.png',
    '03CFA0.rgba32.png',
]
