format = 'ia'
bitdepth = 8
width = 64
height = 64
images = [
    '00E038_0.ia8.png',
    '00E038_1.ia8.png',
    '00E038_2.ia8.png',
    '00E038_3.ia8.png',
    '00E038_4.ia8.png',
    '00E038_5.ia8.png',
    '00E038_6.ia8.png',
    '00E038_7.ia8.png',
    '00E038_8.ia8.png',
    '00E038_9.ia8.png',
]
