format = 'ia'
bitdepth = 16
width = 16
height = 16
images = [
    '005FC8_0.ia16.png',
    '005FC8_1.ia16.png',
    '005FC8_2.ia16.png',
    '005FC8_3.ia16.png',
    '005FC8_4.ia16.png',
    '005FC8_5.ia16.png',
    '005FC8_6.ia16.png',
    '005FC8_7.ia16.png',
]
