format = 'ci'
bitdepth = 4
width = 32
height = 32
images = [
    '0312A8.ci4.png',
    '0314A8.ci4.png',
    '0316A8.ci4.png',
    '0318A8.ci4.png',
    '031AA8.ci4.png',
    '031CA8.ci4.png',
    '031EA8.ci4.png',
    '0320A8.ci4.png',
]
